#!/usr/bin/env python3
"""Paired Wilcoxon/Holm analyses for revision sensitivity experiments.

Expected inputs:
- results/ablation_subject_level.csv (original EdgeNetTF subject-level results)
- results/revision/hyperparameter_subject_level.csv (generated by run_hyperparameter_sensitivity.py)
- results/revision/fft_window_subject_level.csv (generated by run_fft_window_sensitivity.py)

Holm correction is applied separately within each metric family.
"""

from pathlib import Path
import numpy as np
import pandas as pd
from scipy.stats import wilcoxon
from statsmodels.stats.multitest import multipletests

ROOT=Path(__file__).resolve().parents[2]
RESULTS=ROOT/'results'; REV=RESULTS/'revision'
METRICS=['Raw_Acc','Raw_F1_Macro','Causal5_Acc','Causal5_F1_Macro']


def original_edge():
    df=pd.read_csv(RESULTS/'ablation_subject_level.csv')
    return df[df['Variant']=='EdgeNetTF'].sort_values('Subject').reset_index(drop=True)


def paired_rows(df_a, df_b, name_a, name_b):
    rows=[]
    a=df_a.sort_values('Subject').reset_index(drop=True); b=df_b.sort_values('Subject').reset_index(drop=True)
    assert np.array_equal(a['Subject'].to_numpy(),b['Subject'].to_numpy())
    for metric in METRICS:
        x=a[metric].to_numpy(float); y=b[metric].to_numpy(float); stat,p=wilcoxon(x,y,alternative='two-sided')
        rows.append({'Comparison':f'{name_a} vs {name_b}','Metric':metric,'N':len(x),'Mean_Difference_B_minus_A':(y-x).mean(),'Wilcoxon_W':stat,'p_raw':p})
    return rows


def holm_by_metric(df):
    out=[]
    for metric,g in df.groupby('Metric',sort=False):
        g=g.copy(); g['p_Holm']=multipletests(g['p_raw'].to_numpy(),method='holm')[1]; g['Significant_Holm']=g['p_Holm']<0.05; out.append(g)
    return pd.concat(out,ignore_index=True)


def main():
    REV.mkdir(parents=True,exist_ok=True); orig=original_edge()
    hp=pd.read_csv(REV/'hyperparameter_subject_level.csv')
    rows=[]
    for variant in ['kernel_small','kernel_large','channel_narrow','channel_wide']:
        rows += paired_rows(orig,hp[hp['Variant']==variant],'original',variant)
    hp_stats=holm_by_metric(pd.DataFrame(rows)); hp_stats.to_csv(REV/'hyperparameter_statistics_recomputed.csv',index=False)

    fft=pd.read_csv(REV/'fft_window_subject_level.csv'); rows=[]
    hann=fft[fft['FFT_Window']=='hann']; hamming=fft[fft['FFT_Window']=='hamming']
    rows += paired_rows(orig,hann,'original','hann'); rows += paired_rows(orig,hamming,'original','hamming'); rows += paired_rows(hann,hamming,'hann','hamming')
    fft_stats=holm_by_metric(pd.DataFrame(rows)); fft_stats.to_csv(REV/'fft_window_statistics_recomputed.csv',index=False)
    print(hp_stats.to_string(index=False)); print('\n',fft_stats.to_string(index=False))

if __name__=='__main__': main()
